package helpers

import (
	//"fmt"
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	database "main/db"
	"net/http"
	"net/http/cookiejar"
	"os"

	//"golang.org/x/tools/go/analysis/passes/nilfunc"
)

var cookieJar, _ = cookiejar.New(nil)

var client = &http.Client{
	Jar: cookieJar,
}

func sendWebhookMessage(product database.Product) {
	type Author struct {
		Name    string `json:"name"`
		URL     string `json:"url"`
		IconURL string `json:"icon_url"`
	}
	type Fields struct {
		Name   string `json:"name"`
		Value  string `json:"value"`
		Inline bool   `json:"inline,omitempty"`
	}
	type Thumbnail struct {
		URL string `json:"url"`
	}
	type Image struct {
		URL string `json:"url"`
	}
	type Footer struct {
		Text    string `json:"text"`
		IconURL string `json:"icon_url"`
	}
	type Embeds struct {
		Author      Author    `json:"author"`
		Title       string    `json:"title"`
		URL         string    `json:"url"`
		Description string    `json:"description"`
		Color       int       `json:"color"`
		Fields      []Fields  `json:"fields"`
		Thumbnail   Thumbnail `json:"thumbnail"`
		Image       Image     `json:"image"`
		Footer      Footer    `json:"footer"`
	}
	type AutoGenerated struct {
		Username  string   `json:"username"`
		AvatarURL string   `json:"avatar_url"`
		Content   string   `json:"content"`
		Embeds    []Embeds `json:"embeds"`
	}
	payload := &AutoGenerated{
		Username:  "PyroPreme Monitor",
		AvatarURL: "https://media.discordapp.net/attachments/742075074445836368/816390776073748540/PyroPreme-03_3.png?width=676&height=676",
		Content:   "",
		Embeds: []Embeds{
			{
				Title:       product.Name,
				Description: "In Stock",
				URL: fmt.Sprintf("https://supremenewwork.com/shop/%d", product.ID),
				Color:       7405312,
				Fields: []Fields{
					{
						Name:   "Color",
						Value:  product.Color,
						Inline: true,
					},
					{
						Name:   "Sizes",
						Value:  product.Sizes,
						Inline: true,
					},
				},
				Thumbnail: Thumbnail{
					URL: fmt.Sprintf("https:%s",product.Image),
				},
				Footer: Footer{
					Text: "PyroPreme",
				},
			},
		},
	}

	payloadBuf := new(bytes.Buffer)
	_ = json.NewEncoder(payloadBuf).Encode(payload)
	webhookURL := os.Getenv("DISCORD_WEBHOOK_URL")
	if webhookURL == ""{
		panic("DISCORD_WEBHOOK_URL environmental variable not set")
	}
	SendWebhook, err := http.NewRequest("POST", webhookURL, payloadBuf)
	if err != nil {
		log.Fatal(err)
	}

	SendWebhook.Header.Set("content-type", "application/json")

	sendWebhookRes, err := client.Do(SendWebhook)
	//resp, _ := ioutil.ReadAll(sendWebhookRes.Body)
	_ = sendWebhookRes.Body.Close()
	if err != nil {
		log.Fatal(err)
	}
}
